name: Build Game and Watch Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Fix IDF Component Manager Lock
      run: |
        cd gandw_demo_single_screen
        rm -f dependencies.lock

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: 'v6.0'
        target: 'esp32s3'
        path: 'gandw_demo_single_screen'

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: game_and_watch_firmware
        path: gandw_demo_single_screen/build/*.bin

